[ids]

*
##########################################################################




[main]
tab = overload(adjacent_window_navigation, tab)
capslock = overload(nav, esc)

# enable special chars without shift
# can have default behavior holding by shift
# or by switching to the `normal_number_input` layer
# leftalt + rightalt key combo
1 = !
2 = @
3 = #
4 = $
5 = %
6 = ^
7 = &
8 = *
9 = (
0 = )
##########################################################################




# Holding both shift keys activates capslock
# Holding the first shift make keyd jump to this layer
# tapping the second shift enables capslock!
[shift]
leftshift = capslock
rightshift = capslock

1 = 1
2 = 2
3 = 3
4 = 4
5 = 5
6 = 6
7 = 7
8 = 8
9 = 9
0 = 0
##########################################################################




# intended to be activate by holding tab from the main layer
[adjacent_window_navigation]
h = f14
j = f15
k = f16
l = f17
# activate window under
u = f18
# undo/reverse focus change
r = www
##########################################################################




# intended to be activated on hold from capslock from the main layer
# and toggled by leftshift when already in the nav layer
[nav]
leftshift = toggle(nav)
esc = clear()

# vim
h = left
j = down
k = up
l = right

# mouse control
# w = kp8
# a = kp4
# s = kp2
# d = kp6
# q = kp7
# e = kp9
# , = leftmouse
# . = middlemouse
# / = rightmouse
# run the following to make sure config will allow mouse control
# gsettings set org.cinnamon.desktop.a11y.keyboard mousekeys-enable true
# gsettings set org.cinnamon.desktop.peripherals.keyboard numlock-state false
# gsettings set org.cinnamon.desktop.a11y.keyboard mousekeys-init-delay 10
# gsettings set org.cinnamon.desktop.a11y.keyboard mousekeys-accel-time 1200
# gsettings set org.cinnamon.desktop.a11y.keyboard mousekeys-max-speed 2000

# playback control
# f1 = mute toggle on thinkpad keyboard with fn+f1
f1 = playpause
# f2 = volume down on thinkpad
f2 = previoussong
# f3 = volume up on thinkpad
f3 = nextsong

end = sleep
##########################################################################




[alt]
leftalt = toggle(normal_number_input)
rightalt = toggle(normal_number_input)
##########################################################################




# intended to be toggled by alt keys from the alt layer
[normal_number_input]
esc = clear()
# can also hit double alt to toggle this layer off.

# have to override default behavior to allow for 1 -> !, 7 -> &, etc.
leftshift = layer(normal_special_char_input)
rightshift = layer(normal_special_char_input)
1 = 1
2 = 2
3 = 3
4 = 4
5 = 5
6 = 6
7 = 7
8 = 8
9 = 9
0 = 0
##########################################################################




# intended to be activated on shift key hold from
# within the normal_number_input layer
[normal_special_char_input:S]
# without this, the capslock function is not available.
# capslock overloaded in main layer to nav layer and esc
leftshift = capslock
rightshift = capslock

1 = !
2 = @
3 = #
4 = $
5 = %
6 = ^
7 = &
8 = *
9 = (
0 = )
