[ids]

*
##########################################################################


[main]
tab = overload(adjacent_window_navigation, tab)
capslock = overload(nav, esc)

# enable special chars without shift
# can have default behavior holding shift
1 = !
2 = @
3 = #
4 = $
5 = %
6 = ^
7 = &
8 = *
9 = (
0 = )
##########################################################################


# Holding both shift keys activates capslock
# Holding the first shift make keyd jump to this layer
# tapping the second shift enables capslock!
[shift]
leftshift = capslock
rightshift = capslock

1 = 1
2 = 2
3 = 3
4 = 4
5 = 5
6 = 6
7 = 7
8 = 8
9 = 9
0 = 0
##########################################################################



[adjacent_window_navigation]
h = f14
j = f15
k = f16
l = f17
# activate window under
u = f18
# undo/reverse focus change
r = www
##########################################################################


[nav]
leftshift = toggle(nav)
esc = clear()

# vim
h = left
j = down
k = up
l = right

# playback control
# f1 = mute toggle on thinkpad keyboard with fn+f1
f1 = playpause
# f2 = volume down on thinkpad
f2 = previoussong
# f3 = volume up on thinkpad
f3 = nextsong

end = sleep

