[ids]

# 8bitdo Retro 18 Numpad
2dc8:5204
#############################################

[main]
backspace = overload(b_modifier, backspace)
esc = overload(c_modifier, =)
calc = toggle(nav)

kpasterisk = timeout(kpasterisk, 150, macro(kprightparen))
kpslash = timeout(kpslash, 150, macro(kpleftparen))
kpplus = timeout(kpplus, 150, macro(^))
kpminus = timeout(kpminus, 150, macro(_))
#############################################

[c_modifier]
kpslash = volumedown
kpasterisk = volumeup
backspace = mute 
#############################################

[b_modifier]
esc = playpause
kpslash = previoussong
kpasterisk = nextsong
#############################################

[nav]
kp8 = up
kp4 = left
kp5 = down
kp6 = right

kpminus = pageup
kpplus = pagedown

