[ids]

# 8bitdo Retro 18 Numpad
2dc8:5204
#############################################

[main]
backspace = overload(b_modifier, backspace)
esc = overload(c_modifier, =)
calc = toggle(nav)
kpasterisk = overload(power_layer, kpasterisk)
#############################################

[power_layer]
backspace = ^
############################################

[c_modifier]
kpslash = volumedown
kpasterisk = volumeup
backspace = mute 
#############################################

[b_modifier]
esc = playpause
kpslash = previoussong
kpasterisk = nextsong
#############################################

[nav]
calc = clear()

kp8 = up
kp4 = left
kp5 = down
kp6 = right

kpminus = pageup
kpplus = pagedown

