[ids]

# 8bitdo Retro 18 Numpad
2dc8:5204
#---------------------------------------------------------------


[main]
esc = overload(audio_ctl, esc)
kpenter = overload(playback_ctl, kpenter)
calc = toggle(nav)

kpasterisk = timeout(kpasterisk, 250, macro(kprightparen))
kpslash = timeout(kpslash, 250, macro(kpleftparen))
kpplus = timeout(kpplus, 250, macro(^))
kp0 = timeout(kp0, 250, macro(comma))
kpdot = timeout(kpdot, 250, macro(%))

# vim. Use without `macro(<key>)` to allow for quicker repeat
kp7 = timeout(kp7, 250, left)
kp8 = timeout(kp8, 250, down)
kp9 = timeout(kp9, 250, up)
kpminus = timeout(kpminus, 250, right)
#---------------------------------------------------------------


[audio_ctl]
kpslash = volumedown
kpasterisk = volumeup
backspace = mute
#---------------------------------------------------------------


[playback_ctl]
kpplus = nextsong
kpminus = previoussong
backspace = playpause
#---------------------------------------------------------------


[nav]
kp8 = up
kp4 = left
kp5 = down
kp6 = right

kpminus = pageup
kpplus = pagedown
#---------------------------------------------------------------
